
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers}  from "./providers";
import Footers from "../components/footer";
import Header from '../components/header'
const inter = Inter({ subsets: ["latin"] });
// import Scroll from "@/components/scroll";
export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 
      <html lang="en">
        <body className={inter.className}>
        <Providers>
          <Header/>
          {/* <Scroll/> */}
          
          {children}
          <Footers/>
      </Providers>
      
          </body>
      </html>
  );
}
